/* Macro Tracker 3.0.0 — local-first UI. No analytics or remote requests. */
(() => {
'use strict';
const C=MacroCore,S=MacroStorage,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=(v,step=1)=>v===null?'—':(Math.round(v/step)*step).toLocaleString('zh-CN',{maximumFractionDigits:2});
const sourceNames={estimate:'估算',label:'标签 / 已知营养',weighed:'称重',legacy:'旧记录 · 来源未标注',unknown:'未估'};
const DRAFT='macro_tracker_minimal_editor_v3';
let db,data,page='today',date=C.today(),busy=false,undo=null,pendingImport=null,editor=null,trigger=null;
const channel='BroadcastChannel' in window?new BroadcastChannel('macro_tracker_minimal_v3'):null;
function day(){return data.days[date]||{date,entries:[],weight:null,coverage:'unknown',target:null};}
function dayFor(draft,which=date){return draft.days[which] ||= {date:which,entries:[],weight:null,coverage:'unknown',target:C.copy(C.getTarget(draft,which)),updatedAt:''};}
function notice(text,canUndo=false,error=false){$('notice').innerHTML=`<div class="banner ${error?'error':''}">${escape(text)} ${canUndo?'<button data-action="undo">撤销</button>':''}</div>`;}
function show(title,html){trigger=document.activeElement;$('sheet-title').textContent=title;$('sheet-body').innerHTML=html;if(!$('sheet').open)$('sheet').showModal();}
function close(){if(busy)return;$('sheet').close();editor=null;trigger?.focus?.();}
function fail(err){console.error(err);const e=$('form-error');if(e)e.textContent=err.message;notice(err.message||'操作未完成。请保留当前页面并导出备份。',false,true);}
function lock(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value);}
async function commit(mutator,message='已保存',options={}){
 if(busy)return false;lock(true);const before=C.copy(data),next=C.copy(data);
 try{mutator(next);next.revision=data.revision+1;await S.write(db,next,data.revision,options);data=next;undo=options.noUndo?null:before;render();notice(message,!!undo);channel?.postMessage('changed');return true;}catch(e){fail(e);return false;}finally{lock(false);}
}
function renderedEntry(e){return `${e.source==='label'||e.source==='weighed'?'':'约 '}${e.calories===null?'热量未估':format(e.calories)+' kcal'} · P ${e.protein===null?'未知':format(e.protein)+' g'}`;}
function defaultPortion(t){return C.scale(t,(t.lastQuantity||t.quantity||1)/(t.quantity||1));}
function savedDraft(){try{return JSON.parse(localStorage.getItem(DRAFT));}catch{return null;}}
function clearDraft(){localStorage.removeItem(DRAFT);}
function persistEditor(){if(!editor)return;try{const form=$('food-form');localStorage.setItem(DRAFT,JSON.stringify({date,editor,values:Object.fromEntries(new FormData(form))}));$('draft-status').textContent='输入草稿已保存';}catch{$('draft-status').textContent='草稿未能保存，请先完成本条记录';}}
function render(){
 document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===page?'page':'false'));
 $('view').innerHTML=page==='review'?reviewHTML():todayHTML();
}
function todayHTML(){
 const d=day(),sum=C.totals(d.entries),t=C.getTarget(data,date),known=d.entries.length&&!sum.missingCalories;
 const calorieLabel=!t?'已记录热量':!known?(d.entries.length?'已知热量':'尚未记录'):sum.calories>t.calories?'较热量目标约多':'距热量目标约剩';
 const calorieValue=!d.entries.length?null:t&&known?Math.abs(t.calories-sum.calories):sum.calories;
 const proteinLabel=sum.missingProtein?'已知蛋白质':!t?'已记录蛋白质':sum.protein>=t.protein?'蛋白质已到参考目标':'蛋白质还差约';
 const proteinValue=!d.entries.length?null:sum.missingProtein||!t||sum.protein>=t.protein?sum.protein:t.protein-sum.protein;
 const quick=[...data.templates].sort((a,b)=>(Number(!!b.pinned)-Number(!!a.pinned))||String(b.lastUsedAt||'').localeCompare(a.lastUsedAt||'')).slice(0,4);
 return `<div class="row"><h1>${date===C.today()?'今天':'当天记录'}</h1><input class="date-field" id="date" type="date" aria-label="记录日期" value="${date}" max="${C.today()}"></div>
 ${!t?'<div class="banner">先记录也可以。设置热量与蛋白目标后显示剩余量。<button data-action="settings">设置目标</button></div>':''}
 <section class="metric" aria-label="热量"><div class="eyebrow">${calorieLabel}</div><div class="number">${format(calorieValue)} <small>kcal</small></div>${t?`<div class="track" aria-hidden="true"><div class="fill" style="width:${Math.min(100,sum.calories/t.calories*100)}%"></div></div>`:''}<div class="muted">${d.entries.length?'已记录约 '+format(sum.calories)+' kcal':'从常吃的一餐开始'}${t?' / 目标 '+format(t.calories)+' kcal':''}</div></section>
 <section class="metric" aria-label="蛋白质"><div class="eyebrow">${proteinLabel}</div><div class="number">${format(proteinValue)} <small>g</small></div><div class="muted">${sum.missingProtein?'有记录未估蛋白质，暂不判断缺口':`已记录约 ${format(sum.protein)} g${t?' / 参考目标 '+format(t.protein)+' g':''}`}</div></section>
 <div class="muted">${sum.missingCalories?'有未估餐，剩余热量暂不可判断':sum.estimated&&d.entries.length?'含估算 · 以已记录食物计算':'以已记录食物计算'}${!navigator.onLine?' · 离线可用':''}</div>
 <button class="primary wide add" data-action="add">＋ 记录一餐 / 食物</button>
 ${savedDraft()?'<button class="wide" data-action="resume">继续未完成的输入</button>':''}
 <div class="row"><h3>常吃</h3><button class="quiet small" data-action="library">全部 / 管理</button></div>
 ${quick.length?`<div class="shortcuts">${quick.map(t=>`<div class="shortcut"><button class="name" data-action="portion" data-id="${escape(t.id)}">${escape(t.name)}<small>${escape(renderedEntry(defaultPortion(t)))} · ${format(t.lastQuantity||t.quantity||1,.01)} ${escape(t.unit||'份')}</small></button><button class="quick" data-action="quick" data-id="${escape(t.id)}" aria-label="添加${escape(t.name)}">＋</button></div>`).join('')}</div>`:'<p class="muted">记录后点“存为常吃”，下次一键添加。</p>'}
 <section class="section"><div class="row"><h3>已记录</h3><span class="muted">${d.entries.length} 条</span></div>${d.recoveredDraft?'<p class="muted">已恢复旧版较新的草稿；原始版本仍在备份中。</p>':''}
 ${d.entries.map(e=>`<div class="entry"><button class="entry-main" data-action="edit" data-id="${escape(e.id)}"><span>${escape(e.name||'这餐')}</span><span class="muted">${escape(renderedEntry(e))}</span></button><div class="entry-actions"><button data-action="favorite" data-id="${escape(e.id)}">存为常吃</button><button data-action="remove" data-id="${escape(e.id)}">移除</button></div></div>`).join('')||'<div class="empty">今天还没有记录。</div>'}
 ${d.entries.length?`<label class="check"><input id="coverage" type="checkbox" ${d.coverage==='complete'?'checked':''} ${sum.missingCalories?'disabled':''}>今天已记全，估算也算</label><div class="muted small">${sum.missingCalories?'先补上未估餐的热量，再确认全天完整。':'每条记录已自动保存；此项仅说明是否漏餐。'}</div>`:''}</section>
 <div class="section row"><span class="muted">体重 ${d.weight===null?'未记录':format(d.weight,.01)+' kg'}</span><button class="quiet" data-action="weight">${d.weight===null?'记录体重':'修改体重'}</button></div>`;
}
function reviewHTML(){
 const w=C.week(data,date),weights=Object.values(data.days).filter(d=>d.weight>0&&d.date>=C.shift(date,-27)&&d.date<=date).sort((a,b)=>a.date.localeCompare(b.date));
 const average=(start,end)=>{const a=weights.filter(d=>d.date>=start&&d.date<=end);return {n:a.length,value:a.length?a.reduce((s,d)=>s+d.weight,0)/a.length:null};};
 const a=average(C.shift(date,-6),date),b=average(C.shift(date,-13),C.shift(date,-7));
 const change=a.n>=3&&b.n>=3?a.value-b.value:null;
 const history=Object.values(data.days).filter(d=>d.date<=date).sort((a,b)=>b.date.localeCompare(a.date));
 return `<div class="row"><h1>回顾</h1><input class="date-field" id="date" type="date" aria-label="回顾截止日期" value="${date}" max="${C.today()}"></div><p class="muted">截至 ${date} 的近 7 天</p><div class="week">${w.dates.map(dt=>`<button data-action="date" data-date="${dt}" class="${data.days[dt]?.coverage==='complete'?'complete':''}"><span>${['日','一','二','三','四','五','六'][new Date(dt+'T12:00:00').getDay()]}</span><b>${Number(dt.slice(-2))}</b><span>${data.days[dt]?.coverage==='complete'?'记全':data.days[dt]?.entries.length?'未确认':'—'}</span></button>`).join('')}</div>
 <div class="review-stat row"><span>完整记录</span><strong>${w.complete} / 7 天</strong></div><div class="review-stat row"><span>完整日平均热量</span><strong>${w.average===null?'—':'约 '+format(w.average,10)+' kcal'}</strong></div><div class="review-stat row"><span>蛋白达到参考目标</span><strong>${w.proteinMet} / ${w.proteinDays} 可判断日</strong></div><p class="muted small">缺失日不算零摄入。只记录部分日期时，均值不能代表全周。蛋白目标附近的差异不必过度解读。</p>
 <section class="section"><div class="row"><h3>体重 · 近 28 天</h3><button class="quiet" data-action="weight">记录</button></div>${weightChart(weights)}<p>${change===null?'继续观察趋势':`两周均重差 ${change>0?'+':''}${format(change,.01)} kg`}</p><p class="muted">${a.n} 次本周称重 · ${b.n} 次上周称重。${change===null?'每周至少有 3 次同条件称重才显示均重差。':'单周变化可能含水分波动，不自动调整目标。'}</p></section>
 <section class="section"><h3>下一步</h3><p>${w.complete<5?'记录覆盖还不足，暂不根据摄入均值调整目标。':'结合 2–4 周趋势与训练表现回顾目标；不用因某一天超出而补偿。'}</p></section>
 <section class="history"><div class="row"><h3>历史记录</h3><span class="muted">${history.length} 天</span></div><input id="history-search" type="month" aria-label="筛选历史月份"><div id="history-list">${historyRows(history.slice(0,30))}</div>${history.length>30?'<button class="wide quiet" data-action="more-history">显示全部历史</button>':''}</section>`;
}
function historyRows(days){return days.map(d=>`<button data-action="date" data-date="${d.date}"><span>${d.date} · ${d.coverage==='complete'?'已记全':'未确认'}</span><span class="muted">${d.entries.length} 条 · ${d.entries.length?'约 '+format(C.totals(d.entries).calories,10)+' kcal':'无饮食记录'}${d.weight?' · '+format(d.weight,.01)+' kg':''}</span></button>`).join('')||'<p class="muted">没有该月份的记录。</p>';}
function weightChart(rows){if(rows.length<2)return '<p class="empty">记录几次体重后，这里显示变化。</p>';const min=Math.min(...rows.map(d=>d.weight))-.15,max=Math.max(...rows.map(d=>d.weight))+.15;const points=rows.map(d=>({x:46+(new Date(d.date+'T12:00:00')-new Date(C.shift(date,-27)+'T12:00:00'))/86400000/27*390,y:145-(d.weight-min)/(max-min)*120}));return `<svg class="chart" viewBox="0 0 480 180" role="img" aria-label="近28天体重 ${rows.length} 次，最低 ${format(min+.15)}，最高 ${format(max-.15)} 千克"><text x="0" y="24">${format(max,.1)} kg</text><text x="0" y="146">${format(min,.1)}</text><polyline class="line" points="${points.map(p=>p.x+','+p.y).join(' ')}"/>${points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="3"><title>${rows[i].date} ${rows[i].weight} kg</title></circle>`).join('')}<text x="46" y="173">${C.shift(date,-27).slice(5)}</text><text x="420" y="173">${date.slice(5)}</text></svg>`;}
function editorForm(e={},mode='new',saved=null){
 editor={entry:C.copy(e),mode};
 show(mode==='edit'?'编辑记录':mode==='template'?'编辑常吃':'记一餐',`<form id="food-form" class="stack"><div class="row"><button type="button" class="quiet" data-action="library">常吃 / 最近</button><button type="button" class="quiet" data-action="recipe">称重配方</button></div><label>名称 · 可选<input name="name" maxlength="300" value="${escape(e.name||'')}" placeholder="例如：小炒肉盖饭"></label><div class="two"><label>热量 · kcal<input name="calories" type="number" min="0" max="100000" step="any" inputmode="decimal" value="${e.calories??''}" placeholder="可留空标记未估"></label><label>蛋白质 · g<input name="protein" type="number" min="0" max="10000" step="any" inputmode="decimal" value="${e.protein??''}" placeholder="未知可留空"></label></div><p class="muted">填写本次吃下的总量。整餐可只记一条。</p><details><summary>份量、来源与可选营养</summary><div class="stack"><div class="two"><label>当前份量<input name="quantity" type="number" min="0.01" step="any" value="${e.quantity||1}" required></label><label>单位<select name="unit">${['份','g','ml','个'].map(u=>`<option ${e.unit===u?'selected':''}>${u}</option>`).join('')}</select></label></div><p class="muted small">此处是这条营养数值对应的份量；修改它不会自动缩放。复用时按数量自动计算。</p><label>来源<select name="source">${Object.entries(sourceNames).map(([k,v])=>`<option value="${k}" ${(e.source||'estimate')===k?'selected':''}>${v}</option>`).join('')}</select></label><div class="two"><label>碳水 · g<input name="carbs" type="number" min="0" max="10000" step="any" value="${e.carbs??''}"></label><label>脂肪 · g<input name="fat" type="number" min="0" max="10000" step="any" value="${e.fat??''}"></label></div></div></details>${mode==='new'?'<label class="check"><input name="saveTemplate" type="checkbox">同时存为常吃</label>':''}${e.components?.length?'<p class="muted small">此项包含原配方明细，修改合计后会保留原始明细供备份查看；如需重新分配食材，请编辑常吃配方。</p>':''}<div id="form-error" class="error" role="alert"></div><div id="draft-status" class="muted small"></div><button class="primary wide" type="submit">${mode==='template'?'保存常吃':'记入 '+(date===C.today()?'今天':date)}</button><button type="button" class="quiet wide" data-action="discard-draft">放弃本次输入</button></form>`);
 if(saved)Object.entries(saved).forEach(([k,v])=>{const input=$('food-form').elements.namedItem(k);if(input){if(input.type==='checkbox')input.checked=true;else input.value=v;}});
 $('food-form').addEventListener('input',persistEditor);$('food-form').addEventListener('change',persistEditor);
 $('food-form').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target);const out={...C.entry(e),name:String(f.get('name')).trim(),source:f.get('source'),quantity:Number(f.get('quantity')),unit:f.get('unit')};C.fields.forEach(k=>out[k]=C.num(f.get(k)));
  if(!out.name&&out.calories===null&&out.protein===null){$('form-error').textContent='请填写名称或至少一个营养数值；未知餐可只写名称。';return;}
  if(!out.name)out.name='这餐';
  if(e.components?.length&&C.fields.some(k=>out[k]!==e[k])){out.legacyComponents=C.copy(e.components);delete out.components;}
  const ok=await commit(next=>{if(mode==='template'){const i=next.templates.findIndex(t=>t.id===e.id);if(i<0)throw Error('常吃条目已不存在');next.templates[i]={...out,updatedAt:new Date().toISOString()};return;}const d=dayFor(next);if(mode==='edit'){const i=d.entries.findIndex(x=>x.id===e.id);if(i<0)throw Error('原记录已不存在');d.entries[i]=out;}else{out.id=C.uid();d.entries.push(out);}d.coverage='partial';d.updatedAt=new Date().toISOString();if(f.get('saveTemplate'))next.templates.push({...C.copy(out),id:C.uid(),createdAt:new Date().toISOString()});},mode==='template'?'常吃已更新；历史记录保持原值':'已保存');
  if(ok){clearDraft();close();render();}
 };
}
function openAdd(){show('添加',`<div class="stack"><button class="primary wide" data-action="new-entry">输入热量与蛋白 / 留下未估餐</button><button class="wide" data-action="library">从常吃或历史选择</button><button class="quiet wide" data-action="recipe">建立称重配方</button><p class="muted">新的一餐可以先估算。重复的一餐只需确认份量。</p></div>`);}
function library(query=''){
 const matches=t=>(t.name||'').toLowerCase().includes(query.toLowerCase());
 const templates=data.templates.filter(matches).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||String(b.lastUsedAt||'').localeCompare(a.lastUsedAt||''));
 const seen=new Set();const recent=Object.values(data.days).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(d=>d.entries).filter(e=>{const key=[e.name,e.calories,e.protein].join('|');if(seen.has(key)||!matches(e))return false;seen.add(key);return true;}).slice(0,20);
 const items=templates.map(t=>`<div class="list-item"><button data-action="portion" data-id="${escape(t.id)}">${t.pinned?'· ':''}${escape(t.name)}<small>${escape(renderedEntry(t))}</small></button><button data-action="template-menu" data-id="${escape(t.id)}">管理</button><button data-action="quick" data-id="${escape(t.id)}" aria-label="添加${escape(t.name)}">＋</button></div>`).join('');
 return `<h3>常吃 · ${templates.length}</h3>${items||'<p class="muted">还没有匹配的常吃。</p>'}<h3 class="section">最近记录</h3>${recent.map(e=>`<div class="list-item"><button data-action="recent" data-id="${escape(e.id)}">${escape(e.name||'这餐')}<small>${escape(renderedEntry(e))}</small></button></div>`).join('')}`;
}
function openLibrary(){show('常吃与最近',`<input id="library-search" type="search" placeholder="搜索自己的记录" aria-label="搜索常吃与历史"><div class="list" id="library-list">${library()}</div><button class="wide quiet section" data-action="new-entry">直接输入新的一餐</button>`);$('library-search').oninput=e=>$('library-list').innerHTML=library(e.target.value);}
function findEntry(id){return Object.values(data.days).flatMap(d=>d.entries).find(e=>e.id===id);}
function portion(t,isTemplate=true){
 show('确认份量',`<form id="portion-form" class="stack"><h3>${escape(t.name)}</h3><p class="muted">基准 ${format(t.quantity||1,.01)} ${escape(t.unit||'份')} · ${escape(renderedEntry(t))}</p><label>本次吃了多少 · ${escape(t.unit||'份')}<input id="portion" type="number" min="0.01" max="100000" step="any" inputmode="decimal" value="${t.lastQuantity||t.quantity||1}" required></label><div class="row"><button type="button" data-factor="0.5">半份</button><button type="button" data-factor="1">原份量</button><button type="button" data-factor="1.5">1.5 倍</button></div><p id="portion-preview"></p><p class="muted small">按相同配比缩放。只改变主食或肉量时，请改本次记录的具体数值。</p><div id="form-error" class="error" role="alert"></div><button class="primary wide" type="submit">记入 ${date===C.today()?'今天':date}</button><button class="quiet wide" type="button" id="portion-custom">编辑本次数值</button></form>`);
 const update=()=>{try{$('portion-preview').textContent=renderedEntry(C.scale(t,Number($('portion').value)/(t.quantity||1)));}catch{$('portion-preview').textContent='请输入大于零的份量';}};update();$('portion').oninput=update;
 $('portion-form').querySelectorAll('[data-factor]').forEach(b=>b.onclick=()=>{$('portion').value=(t.quantity||1)*Number(b.dataset.factor);update();});
 $('portion-custom').onclick=()=>{try{const e=C.scale(t,Number($('portion').value)/(t.quantity||1));delete e.id;editorForm(e);}catch(e){fail(e);}};
 $('portion-form').onsubmit=async e=>{e.preventDefault();await addTemplate(t,Number($('portion').value)/(t.quantity||1),isTemplate);};
}
async function addTemplate(t,factor=1,isTemplate=true){const e=C.scale(t,factor);e.id=C.uid();e.templateId=isTemplate?t.id:null;const ok=await commit(next=>{const d=dayFor(next);d.entries.push(e);d.coverage='partial';d.updatedAt=new Date().toISOString();const template=next.templates.find(x=>x.id===t.id);if(template){template.lastUsedAt=new Date().toISOString();template.usageCount=(template.usageCount||0)+1;template.lastQuantity=e.quantity;}},'已添加 '+t.name);if(ok)close();}
function templateMenu(t){show(t.name,`<div class="stack"><button class="wide" id="edit-template">${t.components?.length?'编辑配方明细':'编辑默认数值'}</button><button class="wide" id="pin-template">${t.pinned?'取消置顶':'置顶到常吃前列'}</button><button class="wide quiet" id="delete-template">移出常吃（保留历史）</button><div id="form-error" role="alert" class="error"></div></div>`);$('edit-template').onclick=()=>t.components?.length?recipe(t):editorForm(t,'template');$('pin-template').onclick=async()=>{if(await commit(n=>{const x=n.templates.find(x=>x.id===t.id);x.pinned=!x.pinned;},'已更新常吃排序'))close();};$('delete-template').onclick=async()=>{if(await commit(n=>n.templates=n.templates.filter(x=>x.id!==t.id),'已移出常吃'))close();};}
function recipe(t=null){
 const components=C.copy(t?.components||[{name:'',calories:null,protein:null}]);
 show('常吃配方',`<form id="recipe-form" class="stack"><label>配方名称<input id="recipe-name" value="${escape(t?.name||'')}" required maxlength="300" placeholder="例如：家常鸡肉饭"></label><p class="muted">填写各原料在整锅中贡献的热量与蛋白。注意生熟口径，计入烹调油。这里只计算你提供的数值。</p><div id="components"></div><button type="button" id="add-component">＋ 原料</button><div class="two"><label>成品总量<input id="recipe-quantity" type="number" min="0.01" max="100000" step="any" value="${t?.quantity||1}" required></label><label>单位<select id="recipe-unit"><option ${t?.unit==='g'?'selected':''}>g</option><option ${!t||t.unit==='份'?'selected':''}>份</option></select></label></div><p class="muted small">整锅称重就填成品克数；均匀分装也可以填总份数。以后只输入吃下的量。</p><div id="form-error" class="error" role="alert"></div><button class="primary wide">保存为常吃</button></form>`);
 function paint(){$('components').innerHTML=components.map((c,i)=>`<div class="component"><div class="row"><label style="flex:1">原料 ${i+1}<input data-i="${i}" data-k="name" value="${escape(c.name)}" placeholder="名称 / 生熟口径" required></label><button type="button" data-remove="${i}" aria-label="移除原料${i+1}">移除</button></div><div class="two"><label>此原料总 kcal<input type="number" min="0" max="100000" step="any" data-i="${i}" data-k="calories" value="${c.calories??''}" required></label><label>此原料总蛋白 g<input type="number" min="0" max="10000" step="any" data-i="${i}" data-k="protein" value="${c.protein??''}"></label></div></div>`).join('');}
 paint();$('components').oninput=e=>{if(e.target.dataset.i!==undefined)components[e.target.dataset.i][e.target.dataset.k]=e.target.dataset.k==='name'?e.target.value:C.num(e.target.value);};$('components').onclick=e=>{if(e.target.dataset.remove!==undefined){components.splice(Number(e.target.dataset.remove),1);paint();}};$('add-component').onclick=()=>{components.push({name:'',calories:null,protein:null});paint();};
 $('recipe-form').onsubmit=async e=>{e.preventDefault();if(!components.length){$('form-error').textContent='至少填写一种原料';return;}const entries=components.map(c=>C.entry({...c,source:'weighed'})),sum=C.totals(entries);const out={...t,id:t?.id||C.uid(),name:$('recipe-name').value.trim(),components:entries,calories:sum.calories,protein:sum.missingProtein?null:sum.protein,carbs:entries.every(e=>e.carbs!==null)?sum.carbs:null,fat:entries.every(e=>e.fat!==null)?sum.fat:null,source:'weighed',quantity:Number($('recipe-quantity').value),unit:$('recipe-unit').value,updatedAt:new Date().toISOString()};if(await commit(n=>{if(t)n.templates[n.templates.findIndex(x=>x.id===t.id)]=out;else n.templates.push(out);},'配方已保存，历史记录保持原值'))close();};
}
function weight(){show('记录体重',`<form id="weight-form" class="stack"><p class="muted">${date} · 尽量在相似条件下称重，无需每天必填。</p><label>kg<input id="weight-input" type="number" min="1" max="500" step="0.01" inputmode="decimal" value="${day().weight??''}" placeholder="留空可清除当天体重"></label><div id="form-error" class="error" role="alert"></div><button class="primary wide">保存</button></form>`);$('weight-form').onsubmit=async e=>{e.preventDefault();if(await commit(n=>{dayFor(n).weight=C.num($('weight-input').value);},'体重已保存'))close();};}
function settings(){
 const t=C.getTarget(data,C.today());
 show('目标与数据',`<form id="target-form" class="stack"><h3>固定每日目标</h3><div class="two"><label>热量 · kcal<input name="calories" type="number" min="500" max="10000" step="1" value="${t?.calories||''}" required></label><label>蛋白质 · g<input name="protein" type="number" min="1" max="1000" step="1" value="${t?.protein||''}" required></label></div><p class="muted small">${escape(t?.source||(t?'使用当前已保存目标':'请使用你已确定的目标'))}。目标不会因训练日或单次体重自动改变。</p><div id="form-error" class="error" role="alert"></div><button class="primary wide">从今天起使用</button></form><section class="section stack"><h3>数据属于你</h3><button class="wide" data-action="backup">下载完整备份 JSON</button><button class="wide" data-action="csv">导出饮食 CSV</button><button class="wide" data-action="import">导入旧 CSV / 完整备份</button><button class="wide quiet" data-action="original">下载升级前原始数据</button><button class="wide quiet" data-action="old-drafts">查看旧版草稿</button><button class="wide quiet" data-action="recovery">导入前恢复快照</button><p class="muted small">数据保存在当前设备、当前浏览器。建议定期下载完整备份；清除网站数据或换设备后，需要导入备份恢复。</p></section><details><summary>升级与使用说明</summary><p>版本 3.0.0。保留原数据库 macro-tracker-v13 及旧对象，所有新版写入使用独立数据层。首次升级前已在本机保存原始快照。旧记录的 C/F、训练、睡眠等仍保存在完整备份中。</p><p>旧版已保存不代表全天已记全。旧草稿较新且时间戳明确时优先恢复，否则原始草稿保留供查看。不要同时用旧版和新版继续记账；两套数据不双向同步。</p><p>同一浏览器、同一网址来源更新时可自动迁移。换设备、浏览器或域名请导出并导入数据。CSV 是交换格式，完整 JSON 才包含所有模板、目标、未知状态和原始快照。</p></details><div class="muted small">${navigator.onLine?'在线':'离线'} · ${Object.keys(data.days).length} 天记录 · ${data.templates.length} 个常吃</div>`);
 $('target-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),t={calories:Number(f.get('calories')),protein:Number(f.get('protein')),from:C.today(),source:'手动设定'};if(await commit(n=>{n.targets=n.targets.filter(x=>x.from!==t.from);n.targets.push(t);if(n.days[t.from])n.days[t.from].target=C.target(t);},'目标从今天起生效，历史目标未修改'))close();};
}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function backup(){const meta=await S.read(db,'meta');const originals=meta.filter(m=>m.key===S.BACKUP||m.key.startsWith('minimal_v3_before_'));download('macro-tracker-full-'+C.today()+'.json',JSON.stringify({format:'macro-tracker-backup',version:3,exportedAt:new Date().toISOString(),data,originals,editorDraft:savedDraft()},null,2),'application/json');notice('完整备份已生成，请保存在安全位置。');}
async function recovery(){const rows=(await S.read(db,'meta')).filter(r=>r.key.startsWith('minimal_v3_before_')).sort((a,b)=>b.key.localeCompare(a.key));show('导入前恢复快照',`<p class="muted">下载指定快照后，可通过“导入完整备份”恢复。替换重复日期前会再次预览，不会自动删除后来新增的日期。</p>${rows.map((r,i)=>`<div class="list-item"><span style="flex:1">${escape(r.value.at||r.key)}<small>${Object.keys(r.value.previous?.days||{}).length} 天记录</small></span><button data-snapshot="${i}">下载</button></div>`).join('')||'<p>还没有导入前快照。</p>'}`);$('sheet-body').querySelectorAll('[data-snapshot]').forEach(b=>b.onclick=()=>{const row=rows[Number(b.dataset.snapshot)];download('macro-tracker-recovery-'+row.key.slice(18)+'.json',JSON.stringify({format:'macro-tracker-backup',version:3,data:row.value.previous},null,2),'application/json');});}
async function oldDrafts(){const raw=(await S.read(db,'meta',S.BACKUP))?.value;const drafts=raw?.drafts||[];show('升级前草稿',`<p class="muted">原始草稿保留在升级备份。恢复到当天前请确认：这将替换新版同一天的记录，操作可以撤销。</p>${drafts.map((d,i)=>`<div class="list-item"><span style="flex:1">${escape(d.date)}<small>${escape(d.updatedAt||'无时间戳')}</small></span><button data-restore-draft="${i}">预览</button></div>`).join('')||'<p>没有旧版草稿。</p>'}`);$('sheet-body').querySelectorAll('[data-restore-draft]').forEach(b=>b.onclick=()=>{const d=drafts[Number(b.dataset.restoreDraft)];const imported=C.migrate({drafts:[d],dailyTargets:raw.dailyTargets||[]});previewImport(imported,{oldDraft:d});});}
function previewImport(incoming,payload){
 pendingImport={incoming,payload};const overlap=Object.keys(incoming.days).filter(d=>data.days[d]).length;
 show('确认导入',`<div class="stack"><p>${Object.keys(incoming.days).length} 天记录 · ${incoming.templates.length} 个常吃</p><p class="muted">${overlap} 个日期已存在。默认保留现有日期，补入其余记录；同 ID 的常吃也保留现有版本。</p><label class="check"><input id="replace-import" type="checkbox">用导入内容替换重复日期 / 同 ID 常吃</label>${payload.editorDraft?'<label class="check"><input id="import-editor-draft" type="checkbox">恢复备份中的未完成输入</label>':''}${incoming.targets.length?'<label class="check"><input id="import-targets" type="checkbox">同时恢复备份中的目标历史</label>':''}<p class="muted small">导入前会自动保存当前数据快照，原文件内容也留在本机恢复快照内。</p><div id="form-error" class="error" role="alert"></div><button class="primary wide" id="confirm-import">确认导入</button></div>`);
 $('confirm-import').onclick=async()=>{const replace=$('replace-import').checked,targets=$('import-targets')?.checked,restoreDraft=$('import-editor-draft')?.checked,p=pendingImport;const result=C.merge(data,p.incoming,replace);if(targets)result.data.targets=C.copy(p.incoming.targets);const snapshot={previous:C.copy(data),imported:p.payload,at:new Date().toISOString()};const ok=await commit(n=>{Object.assign(n,result.data);},`导入完成：${result.days} 天已导入，${result.skipped} 天保留现有记录`,{snapshot,backupKey:'minimal_v3_before_'+Date.now()});if(ok){if(restoreDraft&&p.payload.editorDraft&&C.validDate(p.payload.editorDraft.date)){try{localStorage.setItem(DRAFT,JSON.stringify(p.payload.editorDraft));}catch{notice('记录已导入，但未完成输入草稿无法保存。',false,true);}}pendingImport=null;close();render();}};
}
$('import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>50*1024*1024)throw Error('文件超过 50 MB，请拆分或使用较小备份');const text=await f.text();let incoming,payload;if(f.name.toLowerCase().endsWith('.json')){payload=JSON.parse(text);incoming=payload.data||payload.schema===3?C.validate(payload.data||payload):Array.isArray(payload.records)||Array.isArray(payload.drafts)?C.migrate(payload):(()=>{throw Error('不支持此 JSON 格式')})();}else{incoming=C.importCSV(text);payload={fileName:f.name,csv:text};}previewImport(incoming,payload);}catch(err){fail(err);}};
document.addEventListener('click',async ev=>{
 const b=ev.target.closest('button');if(!b||busy||!data)return;
 try{if(b.dataset.page){page=b.dataset.page;date=C.today();render();window.scrollTo(0,0);return;}
 const action=b.dataset.action,id=b.dataset.id;
 if(action==='add')editorForm();else if(action==='new-entry')editorForm();else if(action==='edit')editorForm(day().entries.find(e=>e.id===id),'edit');else if(action==='library')openLibrary();else if(action==='recipe')recipe();
 else if(action==='portion')portion(data.templates.find(t=>t.id===id));else if(action==='quick'){const t=data.templates.find(t=>t.id===id);await addTemplate(t,(t.lastQuantity||t.quantity||1)/(t.quantity||1));}else if(action==='recent')portion(findEntry(id),false);else if(action==='template-menu')templateMenu(data.templates.find(t=>t.id===id));
 else if(action==='remove')await commit(n=>{const d=dayFor(n);d.entries=d.entries.filter(e=>e.id!==id);d.coverage='partial';},'记录已移除');
 else if(action==='favorite'){const e=day().entries.find(e=>e.id===id);await commit(n=>n.templates.push({...C.copy(e),id:C.uid(),name:e.name||'常吃的一餐',createdAt:new Date().toISOString()}),'已存为常吃');}
 else if(action==='settings')settings();else if(action==='weight')weight();else if(action==='date'){date=b.dataset.date;page='today';render();window.scrollTo(0,0);}
 else if(action==='undo'&&undo){const old=C.copy(undo);await commit(n=>{Object.assign(n,old);},'已撤销',{noUndo:true});}
 else if(action==='resume'){const draft=savedDraft();if(draft){date=draft.date;page='today';render();editorForm(draft.editor.entry,draft.editor.mode,draft.values);}}
 else if(action==='discard-draft'){clearDraft();close();render();}
 else if(action==='backup')await backup();else if(action==='csv'){download('macro-tracker-'+C.today()+'.csv',C.csvExport(data),'text/csv;charset=utf-8');notice('CSV 已生成；完整备份请使用 JSON。');}
 else if(action==='original'){const row=await S.read(db,'meta',S.BACKUP);download('macro-tracker-original-'+C.today()+'.json',JSON.stringify(row?.value||{},null,2),'application/json');}
 else if(action==='import')$('import-file').click();else if(action==='old-drafts')await oldDrafts();else if(action==='recovery')await recovery();else if(action==='more-history')$('history-list').innerHTML=historyRows(Object.values(data.days).sort((a,b)=>b.date.localeCompare(a.date)));
 }catch(err){fail(err);}
});
document.addEventListener('change',async e=>{if(!data||busy)return;try{if(e.target.id==='date'){if(!C.validDate(e.target.value)||e.target.value>C.today())return;date=e.target.value;render();}else if(e.target.id==='coverage'){const complete=e.target.checked;await commit(n=>{const d=dayFor(n);d.coverage=complete?'complete':'partial';d.confirmedAt=complete?new Date().toISOString():null;},complete?'已标记全天记全':'已改为未确认');}else if(e.target.id==='history-search'){$('history-list').innerHTML=historyRows(Object.values(data.days).filter(d=>!e.target.value||d.date.startsWith(e.target.value)).sort((a,b)=>b.date.localeCompare(a.date)));}}catch(err){fail(err);}});
$('settings').onclick=()=>data&&settings();$('close-sheet').onclick=close;$('sheet').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
window.addEventListener('online',()=>data&&render());window.addEventListener('offline',()=>data&&render());
channel&&(channel.onmessage=()=>notice('另一页面更新了数据。请刷新以读取最新记录；未提交的输入草稿会保留。',false,true));
(async()=>{try{const loaded=await S.init();db=loaded.db;data=loaded.data;render();if(loaded.migrated&&(data.migration.records||data.migration.drafts||data.migration.favorites))notice(`已兼容读取旧记录 ${data.migration.records} 天、草稿 ${data.migration.drafts} 份、常吃 ${data.migration.favorites} 个。原始数据已在本机留存。`);if('serviceWorker' in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');reg.update().catch(()=>{});}catch{notice('记录已载入；离线缓存尚未就绪，联网刷新后重试。');}}navigator.storage?.persist?.().catch(()=>{});}catch(err){$('view').innerHTML='<div class="banner error">数据暂时无法读取。没有清除或覆盖旧数据。请关闭其他旧版页面后刷新；不要清除网站数据。</div>';fail(err);}})();
})();
