/* Preserve all original 2.x object stores. New state and recovery snapshots live in meta. */
(function(root){
'use strict';
const NAME='macro-tracker-v13',KEY='minimal_v3_state',BACKUP='minimal_v3_original_backup';
function open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(NAME,2);r.onupgradeneeded=()=>{const db=r.result;for(const [name,keyPath] of [['records','date'],['favorites','id'],['drafts','date'],['meta','key'],['dailyTargets','date']])if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath});};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('数据库被其他版本占用，请关闭旧版页面后重试'));});}
function read(db,store,key){return new Promise((resolve,reject)=>{const r=key===undefined?db.transaction(store).objectStore(store).getAll():db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function safeParse(s,fallback){try{return JSON.parse(s)||fallback;}catch{return fallback;}}
async function raw(db){const names=['records','favorites','drafts','meta','dailyTargets'];const values=await Promise.all(names.map(n=>read(db,n)));const local={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('macro_tracker_'))local[k]=localStorage.getItem(k);}return {...Object.fromEntries(names.map((n,i)=>[n,values[i]])),localStorage:local,localRecords:safeParse(local.macro_tracker_records_v8,{}),localFavorites:safeParse(local.macro_tracker_favorites_v8,[])};}
function write(db,data,expected,{snapshot,backupKey}={}){return new Promise((resolve,reject)=>{const tx=db.transaction('meta','readwrite'),s=tx.objectStore('meta');let conflict=false;const r=s.get(KEY);r.onsuccess=()=>{const actual=r.result?.value?.revision??null;if(actual!==expected){conflict=true;tx.abort();return;}if(snapshot)s.put({key:backupKey||BACKUP,value:snapshot});s.put({key:KEY,value:data});};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||Error('保存失败'));tx.onabort=()=>reject(Error(conflict?'另一页面已修改数据，请刷新后再操作；当前输入仍保留。':'保存未完成，请重试并导出备份'));});}
async function init(){const db=await open();const existing=await read(db,'meta',KEY);if(existing)return {db,data:MacroCore.validate(existing.value),migrated:false};const snapshot=await raw(db);const data=MacroCore.migrate(snapshot);await write(db,data,null,{snapshot});return {db,data,migrated:true};}
root.MacroStorage={open,read,raw,write,init,KEY,BACKUP};
})(globalThis);
